# Generated by Django 5.1.4 on 2024-12-16 03:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('resident_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('cccd', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'RESIDENT',
            },
        ),
        migrations.CreateModel(
            name='PassportRequest',
            fields=[
                ('passport_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('cccd', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=100)),
                ('current_passport_number', models.CharField(max_length=20)),
                ('verified_status', models.IntegerField(blank=True, null=True)),
                ('approved_status', models.IntegerField(blank=True, null=True)),
                ('user_viewed', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('detail', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'PASSPORT_REQUEST',
            },
        ),
        migrations.CreateModel(
            name='PassportRejection',
            fields=[
                ('reason_id', models.AutoField(primary_key=True, serialize=False)),
                ('reason', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('passport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='passport.passportrequest')),
            ],
            options={
                'db_table': 'PASSPORT_REJECTION',
            },
        ),
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('passport_id', models.AutoField(primary_key=True, serialize=False)),
                ('passport_type', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('reported_date', models.DateField(blank=True, null=True)),
                ('status', models.IntegerField(default=1)),
                ('status_detail', models.CharField(blank=True, max_length=255, null=True)),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='passport.resident')),
            ],
            options={
                'db_table': 'PASSPORT',
            },
        ),
        migrations.CreateModel(
            name='RequestHistory',
            fields=[
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=50)),
                ('value', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_viewed', models.BooleanField(default=False)),
                ('detail', models.CharField(blank=True, max_length=255, null=True)),
                ('passport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='passport.passportrequest')),
            ],
            options={
                'db_table': 'REQUEST_HISTORY',
                'indexes': [models.Index(fields=['history_id'], name='REQUEST_HIS_history_0002be_idx'), models.Index(fields=['passport_id'], name='REQUEST_HIS_passpor_d38bc6_idx'), models.Index(fields=['user_viewed'], name='REQUEST_HIS_user_vi_40752f_idx')],
            },
        ),
    ]
